on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # Выберите нужный дистрибутив (OpenJDK, Oracle JDK и т.д.)

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn clean install
